---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: 10.200.23.116
  remote_user: root

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: 10.200.23.116
  remote_user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: 10.200.23.116
  remote_user: root
  vars: 
    mysqlservice: mysqld
    mysql_port: 3306
    dbuser: foouser
    dbname: foodb
    upassword: abc

  roles:
    - db
