---
# This playbook will install mysql and create db user and give permissions.

- vars: 
    mysqlservice: mysqld
    mysql_port: 3306
    dbuser: foouser
    dbname: foodb
    upassword: abc



- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - mariadb


- name: Start Mysql Service
  service: name=mariadb state=started enabled=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
